import { expect, test } from "@playwright/test";

test("landing page uses the engine-generated banner", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveTitle(/Layered Graphics/);
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Photoshop-like graphics authoring");
  const banner = page.getByAltText("Layered Graphics banner generated by the engine itself");
  await expect(banner).toBeVisible();
  await expect(banner).toHaveJSProperty("naturalWidth", 1200);
  await expect(banner).toHaveJSProperty("naturalHeight", 630);
});

test("Rust/WASM opens and renders the same .kgfx document in a browser", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/playground/");
  const proof = page.locator(".proof");
  await expect(proof).toHaveAttribute("data-proof-state", "ready", { timeout: 30_000 });
  await expect(proof).toHaveAttribute("data-authoring-proof", "ready");
  await expect(page.locator("[data-worker-proof]"))
    .toHaveAttribute("data-worker-proof", "ready", { timeout: 30_000 });
  await expect(page.locator("[data-incremental-proof]"))
    .toHaveAttribute("data-incremental-proof", "ready");
  await expect(page.locator("[data-batch-proof]"))
    .toHaveAttribute("data-batch-proof", "ready");
  await expect(page.locator("[data-equivalence-proof]"))
    .toHaveAttribute("data-equivalence-proof", "ready");
  const interactiveP95 = Number(await page.locator("[data-interactive-p95]").getAttribute("data-interactive-p95"));
  const previewP95 = Number(await page.locator("[data-preview-p95]").getAttribute("data-preview-p95"));
  expect(interactiveP95).toBeLessThanOrEqual(50);
  expect(previewP95).toBeLessThanOrEqual(250);
  expect(Number(await page.locator("[data-main-thread-long-tasks]").getAttribute("data-main-thread-long-tasks"))).toBe(0);
  console.log(`browser preview budgets: interactive p95=${interactiveP95}ms, preview p95=${previewP95}ms`);
  await expect(proof.getByRole("status")).toHaveText("Rendered successfully in this browser.");
  const banner = page.getByAltText("Banner rendered from the .kgfx document by WebAssembly");
  await expect(banner).toBeVisible();
  await expect(banner).toHaveJSProperty("naturalWidth", 1200);
  await expect(banner).toHaveJSProperty("naturalHeight", 630);
  await expect(page.locator("[data-document]")).toContainText("1200×630, revision 13");
  const digest = await banner.evaluate(async (element) => {
    const image = element as HTMLImageElement;
    const bytes = await (await fetch(image.src)).arrayBuffer();
    const hash = await crypto.subtle.digest("SHA-256", bytes);
    return [...new Uint8Array(hash)].map((value) => value.toString(16).padStart(2, "0")).join("");
  });
  expect(digest).toBe("7ed95e67ed629301e2992aa677a38e4027f4baae122985f8adf918395c92032f");
  expect(errors).toEqual([]);
});
