import { expect, test } from "@playwright/test";

test("landing page uses the engine-generated banner", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveTitle(/Layered Graphics/);
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Photoshop-like graphics authoring");
  const banner = page.getByAltText("Layered Graphics banner generated by the engine itself");
  await expect(banner).toBeVisible();
  await expect(banner).toHaveJSProperty("naturalWidth", 1200);
  await expect(banner).toHaveJSProperty("naturalHeight", 630);
});

test("Rust/WASM opens and renders the same .kgfx document in a browser", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/playground/");
  const proof = page.locator(".proof");
  await expect(proof).toHaveAttribute("data-proof-state", "ready", { timeout: 30_000 });
  await expect(page.getByRole("status")).toHaveText("Rendered successfully in this browser.");
  const banner = page.getByAltText("Banner rendered from the .kgfx document by WebAssembly");
  await expect(banner).toBeVisible();
  await expect(banner).toHaveJSProperty("naturalWidth", 1200);
  await expect(banner).toHaveJSProperty("naturalHeight", 630);
  await expect(page.locator("[data-document]")).toContainText("1200×630, revision 13");
  const digest = await banner.evaluate(async (element) => {
    const image = element as HTMLImageElement;
    const bytes = await (await fetch(image.src)).arrayBuffer();
    const hash = await crypto.subtle.digest("SHA-256", bytes);
    return [...new Uint8Array(hash)].map((value) => value.toString(16).padStart(2, "0")).join("");
  });
  expect(digest).toBe("ad100bba1af34fc8d88e891b30f9425b8b032c7d018fa43ff30e773b006c1b1a");
  expect(errors).toEqual([]);
});
