/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeDocument {
  constructor(width: number, height: number, dpi: number)
  static open(bytes: Buffer): NativeDocument
  execute(operationsJson: string, label?: string | undefined | null): string
  undo(): string
  redo(): string
  get historyState(): string
  get manifest(): string
  provideLinkedAsset(id: string, bytes: Buffer): void
  exportKgfx(): Buffer
  render(format: string, optionsJson?: string | undefined | null): Buffer
}

export declare function version(): string
